### ISSUE TITLE
Incorrect BigQueryOptions Types for Oauth

### ISSUE THREAD

**Issue by choxi** [googleapis/nodejs-bigquery#1122]
#### Environment details

  - OS: macOS Monterrey
  - Node.js version: 16.14.2
  - npm version: 7.24.2
  - `@google-cloud/bigquery` version: 6.0.0

#### Steps to reproduce

I'm trying to instantiate the `BigQuery` client with oauth and couldn't find any docs on it. The example I found here works: https://github.com/googleapis/nodejs-bigquery/blob/16d2a505400564cb49210d25f52fccfdaef42dd5/samples/auth-user-sample/authUserFlow.js#L92

But it raises type errors:

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/148144/172864223-f18fa712-c71c-4ae0-8fa0-81117448e9d8.png">

It does function correctly if I ignore the type error, but I'd rather use the correct type if possible. I looked up the types for `BigQueryOptions` which extends `GoogleAuthOptions`, which shows:

```typescript
export interface GoogleAuthOptions<T extends AuthClient = JSONClient> {
    /**
     * An `AuthClient` to use
     */
    authClient?: T;
    /**
     * Path to a .json, .pem, or .p12 key file
     */
    keyFilename?: string;
    /**
     * Path to a .json, .pem, or .p12 key file
     */
    keyFile?: string;
    /**
     * Object containing client_email and private_key properties, or the
     * external account client options.
     */
    credentials?: CredentialBody | ExternalAccountClientOptions;
    /**
     * Options object passed to the constructor of the client
     */
    clientOptions?: JWTOptions | OAuth2ClientOptions | UserRefreshClientOptions | ImpersonatedOptions;
    /**
     * Required scopes for the desired API request
     */
    scopes?: string | string[];
    /**
     * Your project ID.
     */
    projectId?: string;
}
```

So I looked up `Oauth2ClientOptions` and updating my code to pass that type in `clientOptions`:

```js
const credentials = {
  clientId: process.env.GOOGLE_CLIENT_ID,
  clientSecret: process.env.GOOGLE_CLIENT_SECRET,
  refreshToken: this.server.config.oauthRefreshToken,
};

this.conn = new BigQuery({
  clientOptions: credentials,
  projectId: this.database || 'bigquery-public-data',
});
```

But this raises an error:

```
popsql-node-web-1      | Error: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information.
popsql-node-web-1      |     at GoogleAuth.getApplicationDefaultAsync (/app/packages/popsql-core/node_modules/google-auth-library/build/src/auth/googleauth.js:160:19)
popsql-node-web-1      |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
popsql-node-web-1      |     at GoogleAuth.getClient (/app/packages/popsql-core/node_modules/google-auth-library/build/src/auth/googleauth.js:502:17)
popsql-node-web-1      |     at GoogleAuth.authorizeRequest (/app/packages/popsql-core/node_modules/google-auth-library/build/src/auth/googleauth.js:543:24)
```

So for now we're going with the first version, but the types here seem confusing and I'm wondering what the correct implementation should be. 

Thanks for your help!

**Comment by loferris** [comment]
Hi @choxi, 

So the main issue I'm seeing with your solution that's getting the error is, as you noted, a mixup in types. In TypeScript (for clarity), I would interpret/rewrite your code as follows:

`interface OAuth2ClientOptions extends RefreshOptions {
  clientId?: string;
  clientSecret?: string;
  redirectUri?: string;
} ;`
// [docs link]( https://cloud.google.com/nodejs/docs/reference/google-auth-library/latest/google-auth-library/oauth2clientoptions)
// [code link](https://github.com/googleapis/google-auth-library-nodejs/blob/fb40dd7be53dbeb34a10521050fb14e4cc44e6e9/src/auth/oauth2client.ts#L399)

`const credentials: OAuth2ClientOptions = {
  clientId: 'your-client-id',
  clientSecret: 'your-client-secret',
  redirectUri: 'your-redirect-uri', // You did not include this field.
  // refreshToken: 'your-refresh-token' // Here is at least one issue: refreshToken is not a field on this type interface.
};`

`const conn: BigQuery = new BigQuery({
  clientOptions: credentials,
  projectId: 'your-project-id'
});`

As for the initial error, the `credential` object as written does not conform to the type interfaces of [`CredentialBody`](https://github.com/googleapis/google-auth-library-nodejs/blob/fb40dd7be53dbeb34a10521050fb14e4cc44e6e9/src/auth/credentials.ts#L88) or [`ExternalAccountClientOptions`](https://github.com/googleapis/google-auth-library-nodejs/blob/fb40dd7be53dbeb34a10521050fb14e4cc44e6e9/src/auth/externalclient.ts#L37). 

[This `google-auth-library`](https://github.com/googleapis/google-auth-library-nodejs/blob/main/samples/credentials.js) sample shows the correct setup of a generic `CredentialBody` in JS.

[This BQ auth flow sample](https://github.com/googleapis/nodejs-bigquery/blob/main/samples/auth-user-sample/authUserFlow.js) is actually pretty close to the generic OAuth2 sample in the `google-auth-library` repo, and should hopefully work as a pattern to get thinks like refresh tokens passed in your credential object. The issue here is the credential object you gave to the BQ client is just part of the overall `authFlow()` function that returns an object of the correct type. 

Hope this helps!
