### ISSUE TITLE
getQueryResults does not provide response object if not specifying maxResults

### ISSUE THREAD

**Issue by MasterOdin** [googleapis/nodejs-bigquery#1210]
#### Environment details

  - OS: macOS 13.4
  - Node.js version: 16.20
  - npm version: 8.19.4
  - `@google-cloud/bigquery` version: 6.2.0

#### Steps to reproduce

1. Run the following script:
    ```js
    import { BigQuery } from '@google-cloud/bigquery';

    const credentials = {
      /* service_credentials for a given project */
    };

    const bigquery = new BigQuery({
      credentials,
      projectId: credentials.project_id,
    });

    (async () => {
      const [job] = await bigquery.createQueryJob({
        query: 'SELECT 1 AS col',
      });
      const [rows, , response] = await job.getQueryResults({ maxResults: 1 });
      console.log(rows);
      console.log(response);
      const [rows2, , response2] = await job.getQueryResults();
      console.log(rows2);
      console.log(response2);
    })()
      .then(() => console.log('done'))
      .catch((err) => console.error(err));
    ```
2. See that `response` prints out an object that can be used, while `response2` is `undefined`. Order to the calls does not matter

While both `response` and `response2` are typed as `bigquery.IGetQueryResultsResponse | undefined`, it's non-obvious from reading the docs as to when it should be defined vs not.

My use case was wanting to reference `response2.schema` and finding it not defined, and so having to run this initial fetch first to get the schema metadata, and then a second request to get all the rows.

**Comment by alvarowolfx** [comment]
thanks for the report @MasterOdin. 

After digging on that today, I found that the bug is actually on our `@google-cloud-common/paginator` on the `Paginator.extend` method, which defaults to autoPaginate results if `maxResults` is not informed. By doing so, it's overriding the return of the original function and not returning all positional arguments ( like the third argument that you want which contains the table metadata and schema ).

* https://github.com/googleapis/nodejs-bigquery/blob/7f413344ef10b23d487fbb05bf16965c7973034d/src/job.ts#L645
* https://github.com/googleapis/nodejs-paginator/blob/393553cb29b3df4e86d8ede0a19fab1161bc3a8c/src/index.ts#L217

A workaround for now is to pass `{ autoPaginate: false }`, but is not ideal as it will require you to paginate through results. Just wanted to provide an update on that, but I'll need more time to find the proper solution.

**Comment by alvarowolfx** [comment]
You can also call `job.get()` to get the job information and then call `getQueryResults` after that.

```
const [job] = await bigquery.createQueryJob({
  query: 'SELECT 1 AS col',
});
const [response] = await job.get();
console.log(response);      
const [rows] = await job.getQueryResults();
console.log(rows);
```
