### ISSUE TITLE
"querystring"' has no exported member named 'ParsedUrlQueryInput'. Did you mean 'ParsedUrlQuery'

### ISSUE THREAD

**Issue by eljuliperez-meli** [googleapis/nodejs-bigquery#1215]
#### Environment details

  - OS: Mac OS Ventura
  - Node.js version: 16.10.0
  - npm version: 7.24.0
  - `@google-cloud/bigquery` version: from 6.0.2 to 6.2.0
  - Typescript version: ^4.4.2

#### project settings:

NodeJS project with Typescript

#### Steps to reproduce

  1. Install dependency `@google-cloud/bigquery` and create a file with importing the BigQuery function `import { BigQuery } from '@google-cloud/bigquery'`
  2. run `npm run build` and you got the error:

 `"querystring"' has no exported member named 'ParsedUrlQueryInput'. Did you mean 'ParsedUrlQuery'`
![image](https://github.com/googleapis/nodejs-bigquery/assets/133893630/866210ca-da73-42eb-b0af-4f5e137c6a18)

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by alvarowolfx** [comment]
Since your project is using Typescript, @eljuliperez-meli can you confirm which version of the `@types/node` package are you using ? Using any recent version of `@types/node` works just fine, I tested  with `16.10.0` and `20.3.1`. 

Seems like you can be potentially using a really old version of that package. Usually it should align with the NodeJS version that you are targeting, in this case `16.10.0`. I tested installing version `4.9.5` of `@types/node` and I get the same error that you reported, so I assume that's the issue that you're seeing.
