### ISSUE TITLE
Is it possible to retrieve BigQuery Project quotas?

### ISSUE THREAD

**Issue by atrbgithub** [googleapis/nodejs-bigquery#1275]
Hello, 

Is it possible to use this library or another to retrieve the bigquery quota limits and usages?

The compute quotas for example can be retrieved using:

```ts
import { ProjectsClient } from "@google-cloud/compute"
async function getQuotas() {
  const gcpclient = new ProjectsClient()

  const [project] = await gcpclient.get({
    project: "a-test-project",
  })

  console.log(project.quotas)
}
```

I assume this is only the compute quotas though as when running this on a project which has BQ enabled, and has Quotas configured, `Query usage per day` does not appear in the list of quotas returned. 

There doesn't appear to be a relevant reference to quotas in this library. It would be useful to be able to retrieve this information for monitoring purposes. 

Thanks!

**Comment by alvarowolfx** [comment]
@atrbgithub, thanks for the question, but unfortunately currently there is no way to query quota/usage for BigQuery.

**Comment by ryandutton** [comment]
Can this be converted to a feature request?

**Comment by meredithslota** [comment]
Yes, this is a feature request — and specifically, it's a feature request for the BigQuery service to expose this information in a way that clients could consume it, rather than a feature request for this library. There are a handful of existing quota-related feature requests open in the public tracker, here: https://issuetracker.google.com/issues?q=status:open%20componentid:187149%20quota I recommend finding the one that most meets your needs and adding a +1 or additional detail to it. 

Because this isn't a feature request for this specific library, I'm going to close it out. Thanks!
