### ISSUE TITLE
table.insert should (recursively) convert from native types to correct JSON

### ISSUE THREAD

**Issue by tswast** [googleapis/nodejs-bigquery#328]
**Is your feature request related to a problem? Please describe.**

It's frustrating to determine the correct JSON format for each data type when inserting a row with table.insert. For example, if I have a Date object and want to insert it as a TIMESTAMP value in BigQuery, how would I do that? Also, if encoding large integers, I'd have to send as a string (though it's true that JavaScript requires extra modules to support int64)

 **Describe the solution you'd like**

The Python client's insert_rows method converts from native Python type to the correct JSON. It does this recursively so that array and struct columns are also supported.

https://github.com/googleapis/google-cloud-python/blob/64d1dc857f876cc69dcd21e88efa255cf5d3debd/bigquery/google/cloud/bigquery/client.py#L1497

The relevant converters are at

https://github.com/googleapis/google-cloud-python/blob/64d1dc857f876cc69dcd21e88efa255cf5d3debd/bigquery/google/cloud/bigquery/_helpers.py#L311-L436

 **Describe alternatives you've considered**

Alternative: for each column type, document the precise encoding expected (and a helper function for how to convert it).

 **Additional context**

This is in response to @jasonpolites's helpful friction log.

**Comment by callmehiphop** [comment]
I can definitely see how a user would be frustrated after going through the friction log. The client already does convert the native types recursively and we have a static method for every special type. We could document how to correctly encode each data type for every method that inserts data, but I feel like this isn't the best fix since there were still a large number of steps needed to even get to the insert method documentation.

IMO the best solution might be to create more README samples for some of the most common recipes as well as how to handle special types.

**Comment by callmehiphop** [comment]
I'm bumping this down to a p2. I think there are a couple different efforts in motion that should help to resolve this particular issue (samples, new docs site), but I'm not sure if there's anything that can be done immediately.

**Comment by sduskis** [comment]
@callmehiphop, only `type: bug` should have `priority: p*` on it.

**Comment by callmehiphop** [comment]
@bcoe does the new doc site support tutorials?

**Comment by JustinBeckwith** [comment]
I don't believe that's a road we want to go down.  Generally we keep long form content over at cloud.google.com, and save that site just for ref docs.  Given how node.js specific this is though ....

If we did want to do that, including another markdown file with the other content in jsdoc should just work.

**Comment by jasonpolites** [comment]
For any Googler here, internal reference to the friction log is:

go/bq-gh-328

**Comment by steffnay** [comment]
@tswast @jasonpolites I checked out the friction log, but I want to make sure I'm understanding exactly what use case needs to be documented here. Is it showing how to make these ([custom types](https://github.com/googleapis/nodejs-bigquery/blob/179fcdc4b5dbd19c686b98393943e436018fe0e5/src/bigquery.ts#L505)) and demonstrating that the types will be converted during [table.insert()](https://github.com/googleapis/nodejs-bigquery/blob/179fcdc4b5dbd19c686b98393943e436018fe0e5/src/table.ts#L1983) because it calls [encodeValue_()](https://github.com/googleapis/nodejs-bigquery/blob/179fcdc4b5dbd19c686b98393943e436018fe0e5/src/table.ts#L454) ? And/or is it showing how to manipulate native JS Date() objects to get the various BigQuery date types in the correct format?

**Comment by tswast** [comment]
In an ideal world, we'd show how to insert each of the BigQuery-supported data types in a code sample here: https://cloud.google.com/bigquery/streaming-data-into-bigquery

JSDate would be a bonus, but I think just showing what the correct way to insert a TIMESTAMP type would be a big help.

**Comment by steffnay** [comment]
@tswast Something like this? https://github.com/googleapis/nodejs-bigquery/blob/f5c4efedd086e1a6955c6d2faebfbe699009a9dd/samples/insertingDataTypes.js

**Comment by tswast** [comment]
Perfect!

**Comment by tswast** [comment]
https://github.com/googleapis/nodejs-bigquery/blob/f5c4efedd086e1a6955c6d2faebfbe699009a9dd/samples/insertingDataTypes.js#L116 -- probably want to recommend a string for integers for full 64-bit precision.
