### ISSUE TITLE
Using Query Options to Set Destination Table Creates Memory Spike

### ISSUE THREAD

**Issue by andymjames** [googleapis/nodejs-bigquery#340]
#### Environment details

  - OS: AWS Lambda
  - Node.js version: 8.10
  - npm version: 6.5.0
  - `@google-cloud/bigquery` version: ^1.30

#### Steps to reproduce

  1. Materialize a view into a table using DDL and look at the memory. In my Lambda function the RAM usage never goes above about 140 MB.

```JavaScript
const options = {
  query: 'CREATE OR REPLACE TABLE `project.dataset.table` AS SELECT * FROM `project.dataset.view_name`',
  useLegacySql: false, // Use standard SQL syntax for queries.
};

bigquery
    .query(options)
    .then(results => {
      // Success
    });
```

  2. Instead do it by setting query options and look at the RAM usage. My process never dies, but even with 768 MB of RAM this alternate code below will chew up all but ~10% of the RAM.

```JavaScript
const options = {
  query: 'SELECT * FROM `project.dataset.view_name`',
  destinationTable: {
    datasetId: 'dataset',
    projectId: 'project',
    tableId: 'table',
  },
  writeDisposition: 'WRITE_TRUNCATE',
  useLegacySql: false, // Use standard SQL syntax for queries.
};

bigquery
    .query(options)
    .then(results => {
      // Success
    });
```

The behavior is very strange, but my experience was clear. It 256 MB of RAM was way more than enough for making a couple calls with streaming inserts, and as soon as I added an extra call to send a query with destination table settings, my RAM was being chewed up enough to trigger my alert for when a process uses more than 90% of it's available RAM. I boosted and reboosted the max RAM until I got to 768 MB, and when that still used 90%+, I decided to get creative with `CREATE OR REPLACE TABLE table AS`, and suddenly RAM usage is back around 140 MB again.

**Comment by callmehiphop** [comment]
@andymjames The main difference between the two queries you shared is that the latter will actually return results, so increased memory usage should definitely be expected. I am interested to know about how many rows your view contains, since the `query` method will buffer all of them before fulfilling the returned promise.

**Comment by andymjames** [comment]
That explains everything. I made the assumption that setting a destination table was going to mean no results were returned to the code (rerouting them only to the destination table).

The table in question is a little over half a million rows with 8 columns, but in BQ it says it takes less than 50MB of disk space, so while I'm a bit surprised that 50MB of BQ data was somehow requiring at least 10x that in JSON form* (perhaps some of the sparsity I've seen in the data would explain that), the behavior I was seeing I think is explained.

And I don't need the results in my case, so it's great that I can use the DDL and keep my RAM usage smaller. I like that ultimately BQ is offering ways to return the results or not depending on user choice. Maybe there is an opportunity here to find a spot to lay this out more clearly in some docs, but I'm sure finding that spot is much easier said than done.

*Random thought about data size and sparsity from a Xoogler (2012-2017, GH handle matches my Googler one): Does the BQ server deserialize the protos into the JSON form before or after sending to the client? On the one hand, maybe the API (in order to be most compatible with folks not using a client library) must return JSON, but you could save a lot of network traffic in a sparse data situation if the client library had an option ask the API to just send back the proto data with the schema to deserialize it.

**Comment by tswast** [comment]
Hey Andy! 👋 Glad to see you're a BQ user.

Re: Random thought

In the BQ API, we don't send protos over the wire, at least we didn't up until about a month ago with the release of the [BQ Storage API](https://cloud.google.com/bigquery/docs/reference/storage/). With that, you can request the rows via gRPC, but the actual row blocks themselves are serialized via Avro since Avro is actually faster to serialize/deserialize than field-value protos or Any well-known types.

I worked on the Python client for BQ Storage, but we don't yet have a Node client. I'd love to chat sometime to hear about how you might use them if there was a way to quickly get large result sets back in Node.
