### ISSUE TITLE
Can't convert milliseconds timestamp 

### ISSUE THREAD

**Issue by aftabnaveed** [googleapis/nodejs-bigquery#564]
#### Environment details
  - OS: Linux
  - Node.js version: 8.x
  - npm version: 6.x
  - `@google-cloud/bigquery` version:

#### Steps to reproduce
When trying to insert a timestamp which is in milliseconds to BigQuery I get the following error:

```
BigQuery: PartialFailureError  [{"errors":[{"message":"Timestamp field value is out of range:1571872447236999936","reason":"invalid"}],"row":{"startTime":"1571872447237","sessionId":"daccbf09-a8d9-4905-b777-d1c3ab5fb0e9-pzuojj","sessionLength":"22"}}]
```

Here is the actual value of timestamp `1571872447237`

**Comment by steffnay** [comment]
@aftabnaveed Can you show me an example of the code you are using?

**Comment by steffnay** [comment]
@aftabnaveed I double-checked this error and it appears it's because the BigQuery Timestamp type only uses microsecond precision. You can find more info in the docs [here](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#timestamp-type). The fix would be to convert to microseconds before the insertion.

I'm going to close the issue but let me know if there's anything else I can help with for this fix.

**Comment by aftabnaveed** [comment]
@steffnay   I figured it out by converting using the following

```
this.client.timestamp(new Date(parseInt(row.startTime)));  
```

Thanks for looking into it.

**Comment by alex-roboto** [comment]
In case anyone stumbles across this thread in the future, let me clarify, because reading it only made me more confused.

1) OP says they tried to use a timestamp of: 1571872447236999936 as milliseconds since UTC. This is not a valid milliseconds since UTC value. It is much too large. You can check by using this website: https://currentmillis.com/. It's not valid. However, divide by 100,000 and you get: 1571872447236, which IS a valid milliseconds since UTC of: Wed Oct 23 2019 23:14:07. So yes, even if big query accepts milliseconds since UTC... this is not a valid milliseconds since UTC.

2) @steffnay says:
> BigQuery Timestamp type only uses microsecond precision. You can find more info in the docs here. The fix would be to convert to microseconds before the insertion.

A microsecond is _more_ precise than a millisecond. A microsecond is 1/1,000,000th of a second while a millisecond is 1/1,000 of a second. I wouldn't say a Timestamp "only" has microsecond precision versus milliseconds.

3) Assuming Timestamp does internally have microsecond precision... microseconds since UTC will be a HUGE number for most common/modern dates. Javascript's floating point number system simply can't represent them.

So what does this mean? What's the correct way of doing this? Well, using a Date structure seems to be supported by the JavaScript API as @aftabnaveed says. The other guess is to uses milliseconds since UTC (not milliseconds since UTC * 100,000). If that doesn't work... what works for the Java API is to use is a floating point number representing _seconds_ since UTC.

Why is the API using something as odd as seconds instead of milliseconds? I think it has to do with the fact that internally TIMESTAMP has accuracy up to milliseconds. But most programming languages can't support huge numbers. So, using _seconds_ stored in a floating point numbers provides the best accuracy for all programming languages without overflowing.

**Comment by thejaswihn** [comment]
Ran into the same issue and had to convert the timestamp in millis to String in format "YYYY-MM-dd HH:mm:ss.SSS" (java DateTimeFormatter) to get this to work

**Comment by kutsan** [comment]
We were having the same problem and had to convert the date to ISO format.

```javascript
new Date(parsedData.event.event_timestamp_ms).toISOString();
```
