### ISSUE TITLE
Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by AFMiziara** [googleapis/nodejs-bigquery#624]
#### Environment details

  - OS: macOS/Linux
  - Node.js version: 10.17
  - npm version: 6.11
  - `@google-cloud/bigquery` version: 4.6.1

#### Steps to reproduce

  1. Insert some amount of data into bigquery dataset. About ~40k documents (not that big):
```
    this.db.collections.users
      .find({})
      .forEach(doc => {
        if (doc) {
          this.dataset
            .table(table_name)
            .insert(
              {
                  // document format to be inserted
              },
              {
                ignoreUnknownValues: true,
                raw: true,
                templateSuffix: table_suffix
              }
            )
            .catch(err => {
              throw err;
            });
        }
      });
```
  2. Sometimes I'm getting this error:

```
{ FetchError: request to https://bigquery.googleapis.com/bigquery/v2/projects/xxxxxxxxxxx/datasets/xxxxxxxxxxxx/tables/xxxxxxxxxx/insertAll failed, reason: Client network socket disconnected before secure TLS connection was established
at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1453)
at ClientRequest.emit (events.js:198)
at TLSSocket.socketErrorListener (_http_client.js:392)
at TLSSocket.emit (events.js:198)
at emitErrorNT (internal/streams/destroy.js:91)
at emitErrorAndCloseNT (internal/streams/destroy.js:59)
at process._tickCallback (next_tick.js:63)
```

Any ideas how to avoid such error?
Thanks!

**Comment by impactcolor** [comment]
Any updates on this?  Same error.

**Comment by AFMiziara** [comment]
@impactcolor, I found a workaround for cases similar to mine. Looks like using method `insert` is not the best approach when dealing with big amount of data. The best option to avoid connection erros is to create a stream job in BigQuery, by using method `createWriteStream`.

If you are not loading a JSON file, but are working with objects, you can stringify your JSON by using newline delimiters. For more details, you can check this [answer](https://stackoverflow.com/a/49099019/9436122).

Now my streams works smoothly.

**Comment by ernsheong** [comment]
Just saw this today as well on `"@google-cloud/bigquery": "^4.6.1"`

**Comment by zamnuts** [comment]
## Short Answer

You need to await on the asynchronous `insert` before continuing the `forEach` cursor iteration. This code exhausts Node.js' internal socket pool, and is expected behavior when done this way. While the error output is obscure, this is not a bug.

As mentioned previously, the optimal solution is to use `createWriteStream`:
```javascript
// pseudo code, will need more than what is written here to work
const bqInsertWritable = table.createWriteStream();
const objToJsonTransform = toJsonTransform();
const mongoCursorReadable = db.collection.find({});
mongoCursorReadable.pipe(objToJsonTransform).pipe(bqInsertWritable);
```

Let me know if you have further questions, I'm happy to help!

Please let me know if you've confirmed this to be the case and successfully implemented a working solution. I'll leave this issue open for a little while longer.

## Long Answer

I've created a demo app that consistently reproduces this problem, and provides an example of one of many proper implementations. Be sure to view the README, and the linked code within it: https://github.com/zamnuts/bigquery-insert-flooding-diagnostic

I was able to reproduce the originally mentioned error and several others (that follow later):

**TLS Disconnect**
```text
request to https://bigquery.googleapis.com/bigquery/v2/projects/refined-kite-268605/datasets/gh624_dataset/tables/gh624_table2/insertAll failed
  reason: Client network socket disconnected before secure TLS connection was established
```

**Outbound Ephemeral Port Exhaustion**
```text
request to https://bigquery.googleapis.com/bigquery/v2/projects/refined-kite-268605/datasets/gh624_dataset/tables/gh624_table2/insertAll failed
  reason: connect EADDRNOTAVAIL 216.58.192.74:443 - Local (192.168.69.107:0)
```

**Socket Timeout**
```text
network timeout at: https://bigquery.googleapis.com/bigquery/v2/projects/refined-kite-268605/datasets/gh624_dataset/tables/gh624_table2/insertAll
```

This is due to the `insert` calls in the provided code sample not being awaited on, either via async/await, callback, or using the thenable provided by `insert`'s Promise. Instead, 40,000 insert calls happen all at once, flooding the underlying `https.Agent`'s socket pool. This has a negative effect on the Node.js runtime such as serious event loop lag (90 seconds) and unnecessary RAM consumption (1 gigabyte).

From the provided sample code, it appears documents from MongoDB (?) are being read and inserted into BigQuery. The [`cursor.forEach` method provided by MongoDB](https://mongodb.github.io/node-mongodb-native/3.5/api/Cursor.html#forEach) is actually meant to be used asynchronously with the provided (albeit omitted in the sample) `callback`.

To fix it, for each row read from the cursor and subsequently `insert`ed into BigQuery, invoke the `callback` after the individual `insert` Promise settles (either fulfilled or rejected). While not recommended, this approach _will_ work, so long as the asynchronous nature of `insert` is honored.

Initially I thought we could leverage `https.Agent.maxSockets` to buffer and queue the number of concurrent sockets via `@google-cloud/common/util`, but setting it to a value of `1000`, instead of the default `Infinity`, had no effect.

## Possible Enhancements

@bcoe @JustinBeckwith The usage reported herein is incorrect, but we could consider a few ways to prevent this in the future:

1. monitor `teeny-request`'s concurrent socket count, and start emitting warnings about the anti-pattern
2. figure out why `https.Agent.maxSockets` has no effect, and fix it (or maybe I don't know how to use it)
3. include an internal buffer to artificially queue the number of concurrent connections (globally or per API)

Additionally, `teeny-request` and therefore `Table.createWriteStream` requires the Readable to be a string/Buffer; when providing a Readable in object mode, the Stream throws the following error:
```text
TypeError: The "chunk" argument must be one of type string or Buffer. Received type object
```

Providing a way to stream objects to tables would be helpful, currently the only allowed inputs are text files (e.g. json, csv) and GCS references.

**Comment by JustinBeckwith** [comment]
I like the idea of a warning when the concurrent socket count gets out of control.  If `https.Agent.maxSockets` ain't working, could I trouble you to try adding a test to `teeny-request`, and tracking it down?

**Comment by AFMiziara** [comment]
@zamnuts, thanks for the detailed explanation. Warning about the anti-pattern would be a great idea, since there isn't much to to in this case.
