### ISSUE TITLE
Timeout overriding does not works

### ISSUE THREAD

**Issue by Dsiddhesh** [googleapis/nodejs-bigquery#823]
Hi Team,

I want to override default time out value while making call to Big Query operation . I tried passing timeout value with options
`  const options = {
	timeoutMS :1
  }
` But I don't see any effect of this on method . I am not using Job's. Can some one please help me to understand why this is failing and how to override timeout value ?

**Comment by laljikanjareeya** [comment]
@Dsiddhesh  Thanks for the Report. to better understand your problem could you provide the code snippet.

**Comment by Dsiddhesh** [comment]
@laljikanjareeya  Please see below snippet
`  const query = 'SELECT * FROM `bigqueryproject1.datasetparesh.coulmns_50_rows_10000`'
  const options = {
	timeoutMs: 2
  }
  const query1 = await bigqueryClient.query(query,options)
  console.log('******RESULT*****', query1)`

Here I am trying to retrieve data from Table which has large number of records and in options I have specified timeoutMs as 2 miliseconds, So i was expecting timeout error but the query gets executed successfully.  So I was in delima why  the operation dint considered 'timeoutMs' option, or is there any other way to override the timeout value ? I understand that default timeout of BigQuery operation is 10 sec.  Please note I dont intent to use Jobs.

**Comment by Dsiddhesh** [comment]
@laljikanjareeya any updates ?

**Comment by laljikanjareeya** [comment]
@Dsiddhesh  I am looking into it, seems like parameters passing currently in request.

@bcoe  @jkwlui  any thoughts on this, Even I have try with `createJob` with `jobTimeoutMs` and run `job.getQueryResults()` but it also doesn't work.

**Comment by bcoe** [comment]
@laljikanjareeya I don't have much domain expertise in this library, as it's handwritten so a bit of a deviation from our auto-generated libraries.

However, I would start by looking in `@google-cloud/common`, [here](https://github.com/googleapis/nodejs-common/blob/d01507f3fae41ffdffa2056bfb1aa40d97ffb653/src/service.ts).

☝️ this library passes config through to the gaxios transport library, which should in turn be where the timeouts are enforced.

**Comment by Dsiddhesh** [comment]
@laljikanjareeya @bcoe  does that mean if I pass 'timeout' in options while initializing BigqueryClient then t should work ?

**Comment by steffnay** [comment]
@Dsiddhesh @laljikanjareeya There are several different timeout values at play here.

1. Setting `jobTimeoutMs` when creating a job
``` 
const options = { 
  configuration: {
    query: {
      query: `SELECT country_name 
             FROM \`bigquery-public-data.utility_us.country_code_iso\` 
             LIMIT 10`,
      },
    jobTimeoutMs: 1000,
  },
};

const response = await bigquery.createJob(options); 
```
If this time limit is exceeded, BigQuery might attempt to stop the job. It is not guaranteed that BigQuery will successfully stop the job after the timeout has been reached.

2. Setting `timeout` on the BigQuery client constructor.
```

**Comment by steffnay** [comment]
@Dsiddhesh @laljikanjareeya There are several different timeout values at play here.

1. Setting `jobTimeoutMs` when creating a job
``` 
const options = { 
  configuration: {
    query: {
      query: `SELECT country_name 
             FROM \`bigquery-public-data.utility_us.country_code_iso\` 
             LIMIT 10`,
      },
    jobTimeoutMs: 1000,
  },
};

const response = await bigquery.createJob(options); 
```
This value is used to determine the maximum amount of time that the job should run. If this time limit is exceeded, BigQuery might attempt to stop the job. It is not guaranteed that BigQuery will successfully stop the job after the timeout has been reached. If you set the value to 1 when creating a job, it is still possible that the job will not be stopped before the query completes. In this case, you will be able to successfully retrieve query results without interruption.

2. Setting `timeout` on the BigQuery client constructor.
```
const {BigQuery} = require('@google-cloud/bigquery');
const bigquery = new BigQuery({timeout: 1000});
```
This value is used to determine the maximum amount of time (in ms) that the client should wait for a response when making an API request. The default is 60000. This value cannot be used for setting timeouts when getting query results because this value isn't propagated into the request.

3. Setting `timeoutMs` when using `query()` method
```
 const query = 'SELECT * FROM `bigqueryproject1.datasetparesh.coulmns_50_rows_10000`';
  const options = {
	timeoutMs: 2
  };
  const [rows] = await bigqueryClient.query(query, options);
```
The library currently has incorrect documentation for `BigQuery.query()`. In the docs [here](https://github.com/googleapis/nodejs-bigquery/blob/cbca6dcf9c1ed2f6fe718426160c5ab9c1c9e8d5/src/bigquery.ts#L1709) it incorrectly says that the default is to return immediately and that the request will fail with a TIMEOUT error if the timeout has been exceeded. In actuality, the default timeout is 10s and the timeout exceeded response will return with `jobComplete: false`. As the library is currently structured, due to the behavior of auto-paginated requests, `job.getQueryResults()` will continue to poll for results even when a custom timeout has been exceeded. If `options.autoPaginate` is set to `false`, empty rows will be returned when the timeout has been exceeded.

I've opened #872 to change `jobs.getQueryResults()` to return an error if a custom timeout was provided and has been exceeded. Because `BigQuery.query()` uses `jobs.getQueryResults()`, this change will extend to that method.
