### ISSUE TITLE
Could not insert value for Numeric datatype with boundary value

### ISSUE THREAD

**Issue by Dsiddhesh** [googleapis/nodejs-bigquery#847]
Hi Team,
Official documentation mentions that the boundary limit for Numeric type as -99999999999999999999999999999.999999999 to 99999999999999999999999999999.999999999. But using Node library I could insert a value 99999999999999999999999999999.999999999 but I could insert 89999999999999999999999999999.999999999. Does this means the limit mentioned is exclusive of the boundaries ?

**Comment by laljikanjareeya** [comment]
@Dsiddhesh Thanks for reporting.
Probably this is something with javascript because value of `Number.MAX_SAFE_INTEGER` is 9007199254740991.

I tried with 99999999999999999999999999999.999999999 but it throws the below error:
```
Invalid NUMERIC value: 1e+29
```
The work around is you can pass value '99999999999999999999999999999.999999999' in string format.
