### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by IpiVasquez** [googleapis/nodejs-bigquery#859]
#### Environment details

  - OS:
  - Node.js version: 14.8.0
  - npm version: 6.14.7
  - `@google-cloud/bigquery` version: 5.2.0

#### Steps to reproduce

 1. Run the following code with your credentials on a table with a evt_time column of TIMESTAMP type.

```js
import { BigQuery } from '@google-cloud/bigquery';

(async () => {
  const client = new BigQuery();
  const dataset = await client
    .getDatasets()
    .then(([datasets]) => datasets.find((ds) => ds.id === 'dataset'));
  const table = await dataset.table('table_example');
  table
    .insert({
      evt_time: '2014-09-27 12:30:00.00 America/Los_Angeles',
    })
    .then(res => console.log(res))
    .catch((err) => console.log(err.response.insertErrors[0].errors));
})();
```

2. See the response ... I'm getting this:

```
[
  {
    reason: 'invalid',
    location: 'evt_time',
    debugInfo: '',
    message: 'Unrecognized timezone: America/Los_Angeles'
  }
]
```

This is a library issue as I successfully run this on BigQuery GUI:

```SQL
INSERT INTO dataset.table_example
  (evt_time)
VALUES
  ('2014-09-27 12:30:00.00 America/Los_Angeles');
```

Thanks!

**Comment by steffnay** [comment]
Your insert succeeds in the BigQuery UI because the SQL engine converts timestamps with full name timezones into UTC. This conversion does not happen in the backend when inserting data through load jobs or streaming inserts, however. This is why you are getting the error from your table.insert() request.

The option for handling timestamps in this format, without manipulating them, is to leverage the SQL engine's conversion ability by inserting via DML statement, as you did in the UI. Example:
```
const sqlQuery = `INSERT INTO dataset.table_example
                 (evt_time)
              VALUES
                 ('2014-09-27 12:30:00.00 America/Los_Angeles')`

await client.query(sqlQuery);
```
Otherwise, if you want to insert this data via load job or streaming, you will have to first convert these values to another timestamp format.
